.TH INJECT 1 "7 July 2019"
.SH "NAME"
inject \- Substitute STDIN into commands
.SH "SYNOPSIS"
\fBinject\fP [--text] [--delimiter \fIDELIMITER\fP] [--shell \fISHELL\fP] [COMMAND...]
.SH "DESCRIPTION"
\fBinject\fP is a command-line utility that performs text substitution on commands. It allows command line interfaces that do not support being piped a parameter to do exactly that, while providing a great deal of flexibility.

As an example,
.nf
\fBcat /sys/class/power_suppply/BAT1/capacity | inject notify-send "battery: [!]"\fP
.fi
allows notify-send, a cli that does not normally accept piped text, to output the charge in a device's battery without command substitution.
.SH "OPTIONS"
.TP
\-\-delimiter [\fIDELIMITER\fP] | \-d [\fIDELIMITER\fP]
Changes the delimiter used in the find and replace. By default, this is \fB[!]\fP.
.TP
\-\-text | \-t
Prevents the substituted command from being run. Instead, it simply prints it to STDOUT. This is useful for find-and-replace that might not be used in a command.
.TP
\-\-shell [\fISHELL\fP] | \-s [\fISHELL\fP]
Changes the shell the substituted command will be run in. By default, inject will use the environment variable $SHELL. If this is not set, it will fallback to /bin/sh.
